version: "3"
services:
  springapp:
    build: .
    depends_on:
      - db
    container_name: spring_app
    ports:
      - "8080:8080"
    restart: always
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5342:5342"
    volumes:
       - /var/lib/postgresql/data/pgdata
    restart: always
  frontend:
    container_name: frontend
    image: nginx
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - springapp